### ISSUE TITLE
Unhandled exception when login window is closed

### ISSUE THREAD

**Issue by rikyuz** [microsoftgraph/msgraph-training-uwp#27]
I noticed that the demo solutions crash if I close the login window with the title bar close button. The exception message says:

"User canceled authentication. On an Android device, this could be due to the lack of capabilities, such as custom tabs, for the system browser. See https://aka.ms/msal-net-system-browsers for more information."

Please advice how to catch this exception? I already tried to subscribe to the MicrosoftGraphService.Instance.SignInFailed event but it doesn't fire in this situation.

**Comment by rikyuz** [comment]
Here is the stack trace for this exception. It's message is "authentication_canceled"

```
e.Exception.StackTrace

   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.VerifyAuthorizationResult() in C:\Agents\Agent01\_work\27\s\src\Microsoft.Identity.Client\Internal\Requests\InteractiveRequest.cs:line 311
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken) in C:\Agents\Agent01\_work\27\s\src\Microsoft.Identity.Client\Internal\Requests\InteractiveRequest.cs:line 116
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken) in C:\Agents\Agent01\_work\27\s\src\Microsoft.Identity.Client\Internal\Requests\RequestBase.cs:line 154
   at Microsoft.Identity.Client.PublicClientApplication.AcquireTokenForLoginHintCommonAsync(Authority authority, IEnumerable`1 scopes, IEnumerable`1 extraScopesToConsent, String loginHint, UIBehavior behavior, String extraQueryParameters, UIParent parent, ApiIds apiId) in C:\Agents\Agent01\_work\27\s\src\Microsoft.Identity.Client\PublicClientApplication.cs:line 556
   at Microsoft.Identity.Client.PublicClientApplication.AcquireTokenAsync(IEnumerable`1 scopes, String loginHint, UIParent parent) in C:\Agents\Agent01\_work\27\s\src\Microsoft.Identity.Client\PublicClientApplication.cs:line 364
   at Microsoft.Toolkit.Services.MicrosoftGraph.MicrosoftGraphAuthenticationHelper.GetUserTokenV2Async(String appClientId, UIParent uiParent, String redirectUri, String loginHint)
   at Microsoft.Toolkit.Services.MicrosoftGraph.MicrosoftGraphAuthenticationHelper.GetUserTokenV2Async(String appClientId, String loginHint)
   at Microsoft.Toolkit.Services.MicrosoftGraph.MicrosoftGraphService.LoginAsync(String loginHint)
   at Microsoft.Toolkit.Services.MicrosoftGraph.MicrosoftGraphService.TryLoginAsync()
   at Microsoft.Toolkit.Uwp.UI.Controls.Graph.AadLogin.SignInAsync()
   at Microsoft.Toolkit.Uwp.UI.Controls.Graph.AadLogin.AadLogin_Clicked(Object sender, RoutedEventArgs e)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

In the TryLoginAsync method of [MicrosoftGraphService.cs](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/master/Microsoft.Toolkit.Services/Services/MicrosoftGraph/MicrosoftGraphService.cs) this situation should be handled however. It's even in the remarks "Exceptions are not thrown but SignInFailed event is raised". What am I missing here?

**Comment by jasonjoh** [comment]
What is the type of the exception? I notice the toolkit is only catching `MsalServiceException`, I'm betting this is not of that type.

**Comment by rikyuz** [comment]
It appears to be "Microsoft.Identity.Client.MsalClientException".

![gUd4ORr8k0](https://user-images.githubusercontent.com/51473445/67836888-739bcd00-faf6-11e9-8596-b2d1279cfe73.png)

What can be done to fix this issue?

**Comment by jasonjoh** [comment]
You can catch that exception and handle it. It might be worth filing an issue on the toolkit with this detail, they should probably catch that for you.

**Comment by rikyuz** [comment]
I created another issue to the WindowsCommunityToolkit project.

Meanwhile I tried to create my own button which calls the MicrosoftGraphService.Instance.TryLoginAsync() method in a similar manner as AadLogin control. However now I'm facing yet another issue as it causes System.NotImplementedException with message "See https://aka.ms/msal-net-3-breaking-changes".

`ex.StackTrace
   at Microsoft.Identity.Client.PublicClientApplication..ctor(String clientId, String authority)
   at Microsoft.Identity.Client.PublicClientApplication..ctor(String clientId)
   at Microsoft.Toolkit.Services.MicrosoftGraph.MicrosoftGraphAuthenticationHelper.GetUserTokenV2Async(String appClientId, UIParent uiParent, String redirectUri, String loginHint)
   at Microsoft.Toolkit.Services.MicrosoftGraph.MicrosoftGraphAuthenticationHelper.GetUserTokenV2Async(String appClientId, String loginHint)
   at Microsoft.Toolkit.Services.MicrosoftGraph.MicrosoftGraphService.LoginAsync(String loginHint)
   at Microsoft.Toolkit.Services.MicrosoftGraph.MicrosoftGraphService.TryLoginAsync()
   at SkyHighUI.UserControls.NavigationMenu.SignInAsync()`

Can you please help what could cause this? I have tried to understand what happens under the hood in the AadLogin control and MicrosoftGraphService class but can't figure out why this happens with my custom button and not the AadLogin control.

**Comment by jasonjoh** [comment]
Did you add the Microsoft.Identity.Client package to the project? I believe the toolkit installs a specific version (based on MSAL 2) and if you installed MSAL 3 or 4 they introduced a lot of breaking changes (methods in 2 that  no longer exist, etc.)

**Comment by rikyuz** [comment]
Yes, I have version 4.5.1 of Microsoft.Identity.Client installed. I suppose there's no newer version of the [Microsoft Graph Connect Sample for UWP](https://github.com/microsoftgraph/uwp-csharp-connect-sample) which uses a custom login button and doesn't rely on the AadLogin control?

I'm currently trying to upgrade it piece by piece by replacing the obsolete methods with the new ones but I don't know if this is going to help either.

**Comment by rikyuz** [comment]
This issue will be resolved by https://github.com/windows-toolkit/Graph-Controls/issues/22
